### ISSUE TITLE
Have http status code 304 for unmodified storage data?

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-doc#65]
Why? To prevent clients from downloading stuff twice unnecessarily.
What about meta data? I as a client could simply d/l a storage blob and simply do a binary comparison to check whether stuff was modified or not. Storage servers returning 304 would simply shortcut this procedure.

Of course, this would require the clients to send a 'last-modified'-info as well..hmm..I'd eventually opt-in this feature later on though, just for convenience purposes.
[Edit] The server would've logged any download attempts including their ip then anyway..so what's the deal?
https://de.wikipedia.org/wiki/HTTP-Statuscode#3xx_.E2.80.93_Umleitung

**Comment by thechauffeur** [comment]
> there's no need for the server to explicitly return a 304 when nothing has been modified. So yeah, can be closed.

OK, I see :)
