### ISSUE TITLE
Saving buffered data

### ISSUE THREAD

**Issue by k-c13** [Qabel/qabel-doc#70]
During the discussion about acknowledge I found out that we need a JSON structure for buffered data. I do not know a better word. You can find it [here](https://github.com/Qabel/qabel-doc/wiki/Qabel-Buffered-Data).

Please discuss about that.

**Comment by f-porter** [comment]
I miss at least one use case on this page.

**Comment by k-c13** [comment]
I add the test into https://github.com/Qabel/qabel-core/issues/179. A written use case will follow.

**Comment by thechauffeur** [comment]
We have a code example (Qabel/qabel-core#179) for this and a [page](https://github.com/Qabel/qabel-doc/wiki/Qabel-Buffered-Data) in our documentation describing this.

Nevertheless, we do not need this now but later. We need to discuss how helpful this well be without syncing the buffered data.

**Comment by thechauffeur** [comment]
As with the PR we do not need this here right now to be open.
