### ISSUE TITLE
Should we pad Drop Messages?

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel-doc#81]
[Drop Messages](https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Drop#transport-format) currently may have variable sizes. The spec does not talk about padding.
We use padding for Storage Blobs, so why not pad Drop Messages?

I think we have to pad them in order to avoid meta data.

**Comment by roeslpa** [comment]
I agree :+1:

**Comment by thechauffeur** [comment]
We decided to always pad to the max length. We have to update the documentation and the implementation.

**Comment by roeslpa** [comment]
Please review my changes and close if everything is okay:
https://github.com/Qabel/qabel-doc/wiki/Qabel-Protocol-Drop/_compare/1183d19%5E...1183d19
https://github.com/Qabel/qabel-doc/wiki/Qabel-Protocol-Drop/_compare/0367851%5E...0367851
https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Drop/_compare/f6a525f%5E...f6a525f
https://github.com/Qabel/qabel-doc/wiki/Components-Drop/_compare/39dac75%5E...39dac75

**Comment by cburkert** [comment]
Your changes are all valid. Unfortunately, we oversaw a significant problem:
If we keep the total message size constant over time, but change the size of header, key, signature, etc, then the remaining size for the payload will vary. This would have bad effects to the drop message users, because a drop message that fitted well into the payload of version X may be too large for version X+1's payload.
I discussed that with @L-Henke and we both agree, that this is unacceptable. We have to guarantee a minimum payload size.

The solution that came into mind was:
* guarantee a minimum (or a fixed) payload size that we wont fall below in future versions
* for every binary message version define a fixed payload greater or equals to guaranteed size above
* pad all payloads to this defined size and discard larger ones

When it comes to assembling the message, I see two approaches:
1. put the version specific header and tail around it and do no additional padding, which leads to total message sizes that may change over versions
2. define also a fixed total message size, that won't change over versions and pad to this size.
This requires a proper estimation of future changes.

I personally favour the first approach.
Comments welcome.

**Comment by roeslpa** [comment]
I would suggest that we wait until noise is finished and then only pad the plaitext to the max length.
`A' || ENCRYPT(key1, A) || ENCRYPT(key2, plaintext)`
That would guarantee the max length and it would be independent from version modifications.
I guess we can approach the same way right now?!

**Comment by schulze** [comment]
First just some notes about language:
> [...] and then only pad the plaintext to the max length.

When we say "max length" in this discussion we should always explicitly say if we are talking about
* a length for the payload
* or a length for the complete JSON message format
* or a length for the encrypted Data field in the transport format.
* or a length for the complete transport format message

Also, I think we should rather use the terms "fixed length" and "fixed size" if possible. There is a  "maximal length" for the payload (and we need to guarantee a "minimal length" of the payload), but we pad to a fixed size.

Padding only the "data" field in the JSON format, would leak the length of other values of varying size like "acknowledge_id" and "model_object". This would leak which messages are acknowledgements, error notifications, etc. 

Having a constant size of messages in transport format over different versions of the protocol only makes sense if we hide the "Header" field in the transport format, which we don't do at the moment. 

Having a "Data" field of constant size in the transport messages (or JSON messages of constant size) would make sense. I think this is @cburkert's first approach and, at least for the beta, this is the solution I would prefer. It is much simpler and at the moment it is not clear that there is a real benefit in doing the complicated thing.

**Comment by schulze** [comment]
A note about [this](https://github.com/Qabel/qabel-doc/wiki/Qabel-Protocol-Drop/_compare/1183d19%5E...1183d19) change: There is no "ALWAYS" in RFC2119, so think this should be just "always".

**Comment by cburkert** [comment]
When is wrote *payload*, I meant the payload in the binary transport format and not the payload in the json data field. So my payload is the serialized json. Padding this payload does not leak the length of any other json fields.

**Comment by roeslpa** [comment]
I wrote in capitals because someone else did before, but I'm in favour of writing it normally as well. I edited it. When we concluded about the padding I will change it again.
As I wrote I would also say that only the "the encrypted Data field in the transport format" is padded to the defined length.

**Comment by thechauffeur** [comment]
It will be merged into master soon so we need to update the documentation. See Qabel/qabel-core#251.

**Comment by cburkert** [comment]
I updated the documentation. See [diff](https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Drop/_compare/f6a525fd914891e98f69dcd88923cfbcf5307e92...4d25b1d62d144f9831c7213bb168c26da579962a)

**Comment by roeslpa** [comment]
:+1:

**Comment by schulze** [comment]
Keys and signatures are 32 bytes and not 256 bytes.
Otherwise :+1:

**Comment by cburkert** [comment]
@schulze Sure? My calculation and the implementation say different. The signature is as big as the modulus of the RSA key and that is 2048 bit which makes 256 bytes...

**Comment by schulze** [comment]
@cburkert For the keys, I am sure. For the signatures, not at all. I never really got into the details of what OAEP is doing and I failed to find concrete information in the Java documentation. I then gave up, because this will get irrelevant when we switch to noise and elliptic curves (hopefully next week).

**Comment by cburkert** [comment]
@schulze Ok, I just did a quick sanity check and mostly relied on the findings in CryptoUtils. Maybe @roeslpa can tell.

**Comment by schulze** [comment]
No, your 2048 bits is correct. The output of RSA OAEP is the number of bits in the modulus.

**Comment by cburkert** [comment]
We decided to pad drop messages. The documentation has been updated and an issue for the implementation is linked above, so this can be closed.
