### ISSUE TITLE
Change http status code for empty drop from 404 to 204

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel-doc#82]
I'd suggest to change the http status code of a GET or HEAD request of an empty drop from 404 to 204. The reason is, that 4** errors indicate a misbehaviour of the client, which is not the case. The requested drop is just empty.
Therefore, 204 meaning "No content" would fit better here IMO.

EDIT: here the link to the [wiki page](https://github.com/Qabel/qabel-doc/wiki/Qabel-Protocol-Drop#return-values)

**Comment by aBothe** [comment]
Why is there an empty drop after all?

**Comment by cburkert** [comment]
A drop is empty is no one put a message in it or all messages has been discarded.

**Comment by L-Henke** [comment]
I've made the same suggestion half a year ago, but it was declined. https://github.com/Qabel/qabel-doc/issues/6#issuecomment-50325395

**Comment by aBothe** [comment]
@f-porter and I have also been pro changing it to 204 back then.
So, you've got my humble approval for changing it :D

**Comment by cburkert** [comment]
Oh, that explains my déjà vu feeling...
But after reading the first discussion, it doesn't seem that the issue has been settled.
I'd like to reopen the discussion.

**Comment by aBothe** [comment]
To quote @zuckschwerdt: 
>The original reasoning here was: There are no "empty" drops. 
>If a drop is not used or all messages are timed out it will be deleted. Thus the 404 code as this is the default for every (non-existing) drop.
How should a client negotiate new drops then? - Is there documentation about this?

**Comment by aBothe** [comment]
As I doubt that a drop is removed after not being filled with data before a certain amount of time passed (one year or so, this might state that a user won't continue using it again, imho), the server should return a 204 if it's empty, and 404 if the drop has been removed.

Of course, this piece of info might be used to obtain intelligence about whether or when a drop is used, but...not sure whether this information is "leaking" somewhere else anyway.

**Comment by thechauffeur** [comment]
> Of course, this piece of info might be used to obtain intelligence about whether or when a drop is used, but...not sure whether this information is "leaking" somewhere else anyway.

Aye. We should either use 404, or 204 but we should stick with it and always use the same.

My argumentation [was](https://github.com/Qabel/qabel-doc/issues/6#issuecomment-50501178):
> To be honest... I don't really know. Your arguments about 2XX vs. 4XX are correct but nevertheless isn't 404 exactly what we want?
* indicating that the client was able to communicate with a given server
* but the server could not find what was requested.
* A 404 error indicates that the requested resource may be available again in the future;
* however, the fact does not guarantee the same content.

> This exactly describes our situation.

But the second point may be wrong. More correct would be "the server could find what was requested (i.e. the given drop) but there is no content".

**Comment by cburkert** [comment]
We should not argue from the implementation perspective but from the abstract idea behind a drop.
A drop server may allocate its resources only for used drop ids, so one is tempted to say that a drop does not exist if it is not used. However, from the abstract perspective, a drop id is only an address.
And every syntactically valid address should be requestable with an error.
Status code 404 is an error code and therefore not suited for that purpose. The client did nothing wrong. The request was correctly submitted and correctly processed and should therefore be answered with an 2XX status code.

**Comment by thechauffeur** [comment]
As we discussed we could even use 200 with an empty body.

We decided on using 204.

**Comment by thechauffeur** [comment]
Closed by Qabel/qabel-core#282 and Qabel/qabel-drop#15 and an documentation update.
